name: Deploy to Steamship
description: Deploys a Steamship app or plugin.

inputs:
  steamship_key:  # id of input
    description: 'Steamship API Key'
    required: true
  steamship_api_base:  # id of input
    description: 'Steamship API Base'
    required: false
    default: 'https://api.steamship.com/api/v1/'

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install Virtualenv
      shell: bash
      run: |
        python3 -m venv .venv
    - name: Activate Virtualenv
      shell: bash
      run: |
        source .venv/bin/activate
    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install -r requirements.txt
    - name: Install Development Dependencies
      shell: bash
      run: |
        python -m pip install -r requirements.dev.txt
    - name: Run test suite
      shell: bash
      run: |
        pytest
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "14"
    - name: Install Steamship CLI
      shell: bash
      run: npm install -g @steamship/cli

    # Sanity Check:
    #   If the STEAMSHIP_API_KEY variable isn't present, the output of this step will help debug that.
    - name: Require Steamship API Key
      if: ${{ (!(inputs.steamship_key)) }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed("The required `steamship_key` action input was missing.")

    # Sanity Check:
    #   If the STEAMSHIP_API_BASE variable isn't present, the output of this step will help debug that.
    - name: Require Steamship API Base
      if: ${{ (!(inputs.steamship_api_base)) }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed("The required `steamship_api_base` action input was missing.")

    # Debug Check:
    #   Run the `ship user:info` command to log output in GitHub actions that may be helpful debugging a problem.
    - name: Test Steamship Authentication
      shell: bash
      run: ship user:info
      env:
        STEAMSHIP_API_KEY: ${{ inputs.steamship_key }}
        STEAMSHIP_API_BASE: ${{ inputs.steamship_api_base }}

    - name: install strip-ansi-cli
      run: |
        if [ -z "${{ inputs.contains }}" ]; then
            echo 🚧 Installing strip-ansi-cli
            npm install --global strip-ansi-cli
        fi
      shell: bash

    - name: Pipe Steamship auth test to output file
      run: |
        ship user:info &> user_info.txt || true
      shell: bash
      env:
        STEAMSHIP_API_KEY: ${{ inputs.steamship_key }}
        STEAMSHIP_API_BASE: ${{ inputs.steamship_api_base }}

    - name: Check Steamship auth test for pass
      id: check_steamship_auth_for_pass
      run: |
        if grep -q "Handle:" user_info.txt; then
            result=$(echo "PASSED")
        else
            result=$(echo "FAILED")
        echo "::set-output name=result::$(echo $result)"
      shell: bash

    # Sanity Check:
    #   Require PKG_VERSION
    - name: Require Package Version
      if: ${{ (steps.check_steamship_auth_for_pass.outputs.result == 'FAILED') }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed("Steamship authentication failed. Unable to continue deployment.")

    - name: Check Tag Versions
      shell: bash
      id: versions
      run: |
        TAG_VERSION=${GITHUB_REF/refs\/tags\/v/}
        PKG_VERSION=`ship project:get version`
        echo "::set-output name=TAG::$TAG_VERSION"
        echo "::set-output name=PKG::$PKG_VERSION"

    # Sanity Check:
    #   Require PKG_VERSION
    - name: Require Package Version
      if: ${{ (!(steps.versions.outputs.PKG)) }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed("Missing a `version` field in `steamship.json` file.")

    # Sanity Check:
    #   If the user is deploying to a branch tagged vX.Y.Z, then the branch version X.Y.Z must match the steamship.json version.
    - name: Fail if the tags aren't equal
      if: ${{ ( (!(steps.versions.outputs.TAG == 'refs/heads/staging')) && (!(steps.versions.outputs.TAG == 'refs/heads/main')) && (!(steps.versions.outputs.TAG == steps.versions.outputs.PKG)) ) }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed("Deployments to a branch tagged vX.Y.Z must have a matching X.Y.Z version in steamship.json. Branch version (${{ steps.versions.outputs.TAG }}) and the steamship.json version (${{ steps.versions.outputs.PKG }}) are different.")

    # Sanity Check:
    #   Steamship.json type should be plugin or app
    - name: Get the Package Type
      shell: bash
      id: package_type
      run: |
        PKG_TYPE=`ship project:get type`
        TYPE_PLG=plugin
        TYPE_APP=app
        echo "::set-output name=TPE::$PKG_TYPE"
        echo "::set-output name=PLG::$TYPE_PLG"
        echo "::set-output name=APP::$TYPE_APP"
    - name: Require valid type
      if: ${{ (!((steps.package_type.outputs.TPE == steps.package_type.outputs.PLG) || (steps.package_type.outputs.TPE == steps.package_type.outputs.APP))) }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed("The package type (${{ steps.package_type.outputs.TPE }}) must be 'plugin' or 'app' to deploy via this action.")

    # Maybe Deploy the Plugin
    - name: Deploy Plugin
      if: ${{ steps.package_type.outputs.TPE == steps.package_type.outputs.PLG }}
      shell: bash
      run: ship plugin:deploy
      env:
        STEAMSHIP_API_KEY: ${{ inputs.steamship_key }}
        STEAMSHIP_API_BASE: ${{ inputs.steamship_api_base }}

    # Maybe Deploy the App
    - name: Deploy App
      if: ${{ steps.package_type.outputs.TPE == steps.package_type.outputs.APP }}
      shell: bash
      run: ship app:deploy
      env:
        STEAMSHIP_API_KEY: ${{ inputs.steamship_key }}
        STEAMSHIP_API_BASE: ${{ inputs.steamship_api_base }}
branding:
    icon: 'upload-cloud'
    color: 'green'